runtime: go116  # or another supported version

instance_class: F1

main: ./doh-server

handlers:
- url: /dns-query
  secure: always
  script: auto

- url: /.*
  secure: always
  static_files: index.html
  upload: index.html

